"""
app/models/chat_message.py

Individual messages within a chat session.
Each (user question, assistant answer) pair produces two rows —
one with role='user', one with role='assistant'.

Soft delete:
    Messages are soft-deleted (deleted_at set) when clear_history()
    is called. Physical deletion happens after 30 days via the
    cleanup ARQ task. This preserves audit trail while presenting
    a fresh conversation to the user.

Sources (JSONB):
    For assistant messages, stores the RAG source chunks cited
    in the response. Null for user messages.
    Shape matches the SourceChunk schema exactly.
"""

from datetime import datetime
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from sqlalchemy import DateTime, ForeignKey, Index, Integer, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.chat_session import ChatSession
    from app.models.paper import Paper
    from app.models.user import User


class ChatMessage(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    A single message in a (user, paper) conversation.

    role:
        'user'      → message sent by the human user
        'assistant' → response generated by the LLM

    content:
        Full message text. For assistant messages, this is the
        complete streamed response after all chunks have arrived.

    sources:
        JSONB array of SourceChunk objects. Only populated for
        assistant messages. Null for user messages.
        Example:
        [
            {
                "chunk_text": "...",
                "page_number": 4,
                "section": "Methodology",
                "confidence_score": 0.91
            }
        ]

    tokens_used:
        Total tokens consumed by the LLM for this turn (prompt +
        completion). Null for user messages. Used for cost tracking.

    deleted_at:
        Soft delete timestamp. Set by clear_history().
        Messages with deleted_at IS NOT NULL are excluded from
        all user-facing queries. Physical deletion after 30 days.
    """

    __tablename__ = "chat_messages"

    __table_args__ = (
        # Composite index for the most common query pattern:
        # "get all messages for this user+paper pair"
        Index(
            "idx_chat_messages_user_paper",
            "user_id",
            "paper_id",
        ),
        # Index for chronological ordering within a session
        Index(
            "idx_chat_messages_session_created",
            "session_id",
            "created_at",
        ),
        # Partial index for soft-delete filtering
        # Only indexes rows where deleted_at IS NULL (active messages)
        # Makes "WHERE deleted_at IS NULL" queries extremely fast
        Index(
            "idx_chat_messages_active",
            "session_id",
            postgresql_where="deleted_at IS NULL",
        ),
    )

    # ------------------------------------------------------------------
    # Foreign keys
    # ------------------------------------------------------------------
    session_id: Mapped[str] = mapped_column(
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="The session this message belongs to.",
    )

    user_id: Mapped[str] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        comment=(
            "Denormalised user_id for efficient per-user queries "
            "without joining through chat_sessions."
        ),
    )

    paper_id: Mapped[str] = mapped_column(
        ForeignKey("papers.id", ondelete="CASCADE"),
        nullable=False,
        comment=(
            "Denormalised paper_id for efficient per-paper queries "
            "without joining through chat_sessions."
        ),
    )

    # ------------------------------------------------------------------
    # Message content
    # ------------------------------------------------------------------
    role: Mapped[str] = mapped_column(
        nullable=False,
        comment="Message author role. One of: 'user', 'assistant'.",
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment=(
            "Full message text. For assistant messages, this is the "
            "complete response after streaming has concluded."
        ),
    )

    sources: Mapped[Optional[List[Dict[str, Any]]]] = mapped_column(
        JSONB,
        nullable=True,
        default=None,
        comment=(
            "RAG source chunks cited in this response. "
            "Null for user messages. "
            "Array of SourceChunk objects: "
            "{chunk_text, page_number, section, confidence_score}."
        ),
    )

    tokens_used: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        default=None,
        comment=(
            "Total tokens consumed (prompt + completion). "
            "Null for user messages. Used for cost tracking."
        ),
    )

    # ------------------------------------------------------------------
    # Soft delete
    # ------------------------------------------------------------------
    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        index=True,
        comment=(
            "Soft delete timestamp. Set by clear_history(). "
            "Null means the message is active. "
            "Physical deletion occurs 30 days after this timestamp "
            "via the cleanup ARQ task."
        ),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    session: Mapped["ChatSession"] = relationship(
        "ChatSession",
        back_populates="messages",
        lazy="noload",
    )

    user: Mapped["User"] = relationship(
        "User",
        back_populates="chat_messages",
        lazy="noload",
    )

    paper: Mapped["Paper"] = relationship(
        "Paper",
        back_populates="chat_messages",
        lazy="noload",
    )

    def __repr__(self) -> str:
        return (
            f"<ChatMessage "
            f"id={self.id!r} "
            f"role={self.role!r} "
            f"session_id={self.session_id!r} "
            f"deleted_at={self.deleted_at!r}>"
        )