"""
app/models/user.py

Core user model. Represents a registered platform user.

Auth:
    Email + password (v1). OAuth reserved for v2.
    Passwords stored as bcrypt hashes (security.hash_password).
    password_hash is NEVER returned in any API response.

Role:
    'user'  → standard platform user (default)
    'admin' → platform admin (access to /admin/* endpoints)
    Extended roles reserved for future versions.
    Role is checked at the middleware layer (require_admin dependency).

Email verification:
    email_verified=False by default on signup.
    Unverified users receive 403 EMAIL_NOT_VERIFIED on protected routes.
    Set to True when the user consumes a valid verification token.

Relationships:
    This model is the root of the cascade tree. Deleting a user
    cascade-deletes: saved_papers, tags, collections, chat_sessions,
    chat_messages, notifications, refresh_tokens, verification_tokens.
    Papers uploaded by the user are NOT deleted — uploaded_by is SET NULL.
"""

from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Boolean, DateTime, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.chat_message import ChatMessage
    from app.models.chat_session import ChatSession
    from app.models.collection import Collection
    from app.models.notification import Notification
    from app.models.paper import Paper
    from app.models.pipeline_trace import PipelineTrace
    from app.models.refresh_token import RefreshToken
    from app.models.saved_paper import SavedPaper
    from app.models.tag import Tag
    from app.models.verification_token import VerificationToken


class User(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Registered platform user.

    Core fields:
        name             → display name
        email            → unique, used for login and verification
        password_hash    → bcrypt hash, never exposed in API responses
        role             → 'user' or 'admin'
        email_verified   → gates access to protected routes

    Optional fields:
        avatar_url       → URL string (no server-side upload in v1)
        institution      → free-text institutional affiliation
        last_active_at   → updated on authenticated requests (admin stat)
    """

    __tablename__ = "users"

    __table_args__ = (
        # Unique email — enforced at DB level
        Index(
            "idx_users_email",
            "email",
            unique=True,
        ),
        # Admin queries: filter/sort by role
        Index(
            "idx_users_role",
            "role",
        ),
        # Admin queries: sort by created_at
        Index(
            "idx_users_created_at",
            "created_at",
        ),
    )

    # ------------------------------------------------------------------
    # Core fields
    # ------------------------------------------------------------------
    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Display name shown throughout the platform.",
    )

    email: Mapped[str] = mapped_column(
        String(254),
        nullable=False,
        unique=True,
        comment=(
            "Primary email address. Used for login, verification, "
            "and password reset flows. Must be unique across all users."
        ),
    )

    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment=(
            "Bcrypt hash of the user's password. "
            "NEVER returned in any API response. "
            "Generated by security.hash_password()."
        ),
    )

    role: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="user",
        comment=(
            "User role. 'user' (default) or 'admin'. "
            "'admin' grants access to /admin/* endpoints. "
            "Checked by require_admin() dependency."
        ),
    )

    email_verified: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment=(
            "Whether the user has verified their email address. "
            "False by default on signup. "
            "Unverified users receive 403 EMAIL_NOT_VERIFIED "
            "on all protected routes."
        ),
    )

    # ------------------------------------------------------------------
    # Optional profile fields
    # ------------------------------------------------------------------
    avatar_url: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment=(
            "URL to profile avatar image. "
            "May point to Gravatar, CDN, or any HTTPS image URL. "
            "No server-side upload in v1."
        ),
    )

    institution: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        default=None,
        comment="Optional institutional affiliation (e.g. 'MIT CSAIL').",
    )

    # ------------------------------------------------------------------
    # Activity tracking
    # ------------------------------------------------------------------
    last_active_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment=(
            "Timestamp of the user's most recent authenticated request. "
            "Updated periodically (not on every request — debounced). "
            "Used by admin stats (active_users_7d)."
        ),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    # Papers where this user is uploaded_by
    # foreign_keys uses the actual column object via string annotation
    uploaded_papers: Mapped[List["Paper"]] = relationship(
        "Paper",
        back_populates="uploader",
        foreign_keys="[Paper.uploaded_by]", 
        lazy="noload",
    )

    saved_papers: Mapped[List["SavedPaper"]] = relationship(
        "SavedPaper",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    tags: Mapped[List["Tag"]] = relationship(
        "Tag",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    collections: Mapped[List["Collection"]] = relationship(
        "Collection",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    chat_sessions: Mapped[List["ChatSession"]] = relationship(
        "ChatSession",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    chat_messages: Mapped[List["ChatMessage"]] = relationship(
        "ChatMessage",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    notifications: Mapped[List["Notification"]] = relationship(
        "Notification",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    refresh_tokens: Mapped[List["RefreshToken"]] = relationship(
        "RefreshToken",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    verification_tokens: Mapped[List["VerificationToken"]] = relationship(
        "VerificationToken",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    # Pipeline traces triggered by this user
    triggered_pipeline_traces: Mapped[List["PipelineTrace"]] = relationship(
        "PipelineTrace",
        back_populates="triggered_by_user",
        foreign_keys="[PipelineTrace.triggered_by]",
        lazy="noload",
    )

    def __repr__(self) -> str:
        return (
            f"<User "
            f"id={self.id!r} "
            f"email={self.email!r} "
            f"role={self.role!r} "
            f"verified={self.email_verified!r}>"
        )